// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func adminBase(data BaseData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"ru\" class=\"dark\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/admin_base.templ`, Line: 9, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " — ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.SiteName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/admin_base.templ`, Line: 9, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</title><link rel=\"icon\" type=\"image/webp\" href=\"/assets/icon.webp\"><link rel=\"stylesheet\" href=\"/static/output.css\"><script src=\"/static/htmx.min.js\"></script></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<script>\n\t\t\tfunction toggleAdminSidebar(){\n\t\t\t\tvar s=document.getElementById('admin-sidebar');\n\t\t\t\tvar t=s.closest('.admin-sidebar-trigger');\n\t\t\t\ts.classList.toggle('is-open');\n\t\t\t\tif(t) t.classList.toggle('is-open');\n\t\t\t}\n\t\t\tfunction toggleAdminGroup(btn){\n\t\t\t\tbtn.parentElement.classList.toggle('is-open');\n\t\t\t}\n\t\t\tfunction navClick(el, page){\n\t\t\t\tdocument.querySelectorAll('.admin-nav-item').forEach(function(e){e.classList.remove('admin-nav-item-active');});\n\t\t\t\tdocument.querySelectorAll('.admin-nav-sub-item').forEach(function(e){e.classList.remove('admin-nav-sub-item-active');});\n\n\t\t\t\tif(el.classList.contains('admin-nav-sub-item')){\n\t\t\t\t\tel.classList.add('admin-nav-sub-item-active');\n\t\t\t\t\tel.closest('.admin-nav-group').classList.add('is-open');\n\t\t\t\t} else {\n\t\t\t\t\tel.classList.add('admin-nav-item-active');\n\t\t\t\t}\n\t\t\t\treturn true;\n\t\t\t}\n\t\t\t// init active state from current URL on page load (for direct navigation)\n\t\t\t(function(){\n\t\t\t\tvar path=window.location.pathname;\n\t\t\t\tvar map={'/admin':'dashboard','/admin/settings':'settings','/admin/settings/navbar':'navbar','/admin/settings/servers':'servers'};\n\t\t\t\tvar page=map[path];\n\t\t\t\tif(page){\n\t\t\t\t\tvar el=document.querySelector('[data-page=\"'+page+'\"]');\n\t\t\t\t\tif(el) navClick(el,page);\n\t\t\t\t}\n\t\t\t})();\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
