// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func homePage(data BaseData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"max-w-5xl mx-auto px-4 py-20 text-center\"><h1 class=\"text-4xl md:text-5xl font-bold gradient-text mb-4\">CubeNet CMS</h1><p class=\"text-lg text-surface-dimmed max-w-xl mx-auto mb-8\">Open Source CMS для Minecraft модедных серверов</p><a href=\"/servers\" class=\"inline-flex items-center justify-center px-6 py-3 rounded-lg text-base font-medium bg-accent text-white hover:bg-accent-hover transition-colors\">Список серверов</a></section><section class=\"max-w-5xl mx-auto px-4 py-12\"><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\" id=\"server-preview\" hx-get=\"/api/v1/servers\" hx-trigger=\"load\" hx-swap=\"innerHTML\"><div class=\"bg-surface border border-border rounded-lg p-6\">Загрузка...</div></div></section><section class=\"max-w-5xl mx-auto px-4 py-12\"><h2 class=\"text-2xl font-bold text-center mb-8\">Возможности</h2><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\"><div class=\"bg-surface border border-border rounded-lg p-6\"><h3 class=\"text-lg font-semibold mb-2\">Управление серверами</h3><p class=\"text-sm text-surface-dimmed\">Добавляйте и управляйте Minecraft серверами</p></div><div class=\"bg-surface border border-border rounded-lg p-6\"><h3 class=\"text-lg font-semibold mb-2\">Лаунчер</h3><p class=\"text-sm text-surface-dimmed\">Собственный лаунчер с авто-обновлением</p></div><div class=\"bg-surface border border-border rounded-lg p-6\"><h3 class=\"text-lg font-semibold mb-2\">Новости</h3><p class=\"text-sm text-surface-dimmed\">Публикуйте новости вашего проекта</p></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = base(data).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
