// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func registerPage(data BaseData, err string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"relative flex-1 flex items-center justify-center px-4 py-12 overflow-hidden\"><div class=\"orb top-[-10%] left-[-5%] w-[400px] h-[400px] bg-violet-300/12\" style=\"box-shadow: 0 0 140px 60px rgba(167, 139, 250, 0.04);\"></div><div class=\"orb bottom-[-10%] right-[-5%] w-[400px] h-[400px] bg-violet-300/10\" style=\"box-shadow: 0 0 140px 60px rgba(167, 139, 250, 0.03);\"></div><div class=\"relative z-10 glass-strong rounded-3xl w-full max-w-sm p-8\"><div class=\"text-center mb-8\"><h1 class=\"text-2xl font-bold gradient-text mb-1\">Регистрация</h1><p class=\"text-sm text-foreground/60\">Создайте аккаунт</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if err != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex items-center gap-3 px-4 py-3 rounded-2xl mb-6 text-sm\" style=\"background: oklch(57.7% 0.245 27.325 / 0.15); border: 1px solid oklch(57.7% 0.245 27.325 / 0.3);\"><svg class=\"w-5 h-5 shrink-0\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"oklch(57.7% 0.245 27.325)\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 9v3.75m-9.303 2.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z\"></path></svg> <span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(err)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/register.templ`, Line: 17, Col: 17}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form hx-post=\"/auth/register\" hx-target=\"body\" hx-swap=\"outerHTML\" class=\"space-y-5\"><div><label class=\"block text-sm font-medium text-foreground/60 mb-1.5\" for=\"username\">Имя пользователя</label> <input class=\"input-modern\" type=\"text\" id=\"username\" name=\"username\" required placeholder=\"Введите логин\"></div><div><label class=\"block text-sm font-medium text-foreground/60 mb-1.5\" for=\"email\">Почта</label> <input class=\"input-modern\" type=\"email\" id=\"email\" name=\"email\" required placeholder=\"email@example.com\"></div><div><label class=\"block text-sm font-medium text-foreground/60 mb-1.5\" for=\"password\">Пароль</label> <input class=\"input-modern\" type=\"password\" id=\"password\" name=\"password\" required placeholder=\"Введите пароль\"></div><div><label class=\"block text-sm font-medium text-foreground/60 mb-1.5\" for=\"confirm\">Повторите пароль</label> <input class=\"input-modern\" type=\"password\" id=\"confirm\" name=\"confirm\" required placeholder=\"Повторите пароль\"></div><button type=\"submit\" class=\"btn-primary w-full py-3.5\"><svg class=\"w-4 h-4\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z\"></path></svg> Зарегистрироваться</button></form><p class=\"text-sm text-center mt-6 text-foreground/60\">Уже есть аккаунт? <a href=\"/login\" class=\"text-primary hover:underline transition-colors font-medium\">Войти</a></p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = base(data).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
